### ISSUE TITLE
[Question][Compilation error] How to create a qt library ?

### ISSUE THREAD

**Issue by harideva16** [axmetishe/gradle-qt-application-example#3]
according to your suggesstion https://github.com/axmetishe/gradle-qt-application-example/issues/1#issuecomment-914396237 I create a qt library project with gradle.

[myproject][1] and [build.gradle file][2]

But , If I build my project It comes an error like this
![libqt](https://user-images.githubusercontent.com/88296348/132451195-bf6f6feb-7636-4389-88eb-6c31eb8042a7.PNG)

**ERROR**
        10:36:23: Executing task ':assemble'...

    > Task :generateQTResources

    > Task :generateQTSources
    D:\gradle-qt-application-example-master\src\main\meta-headers\untitled.h:0:1: note: No relevant classes found. No output generated.
    D:\gradle-qt-application-example-master\src\main\meta-headers\untitled_global.h:0:1: note: No relevant classes found. No output generated.

    > Task :generateQTUI

    > Task :compileDebugWindowsCpp
    untitled.cpp
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(387): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1261): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1262): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1263): error C7525: inline variables require at least '/std:c++17'
    The contents of <variant> are available only with C++17 or later.
    The contents of <optional> are available only with C++17 or later.
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(58): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(111): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(117): note: see reference to class template instantiation 'QTypeInfoMerger<T,Ts...>' being compiled
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2039: 'optional': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\tuple(24): note: see declaration of 'std'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2065: 'optional': undeclared identifier
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2974: 'QTypeTraits::detail::expand_operator_equal_tuple': invalid template argument for 'T', type expected
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(272): note: see declaration of 'QTypeTraits::detail::expand_operator_equal_tuple'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2988: unrecognizable template declaration/definition
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2143: syntax error: missing ';' before '>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2059: syntax error: '>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2065: 'T': undeclared identifier
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2923: 'QTypeTraits::detail::has_operator_equal': 'T' is not a valid template type argument for parameter '<unnamed-symbol>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): note: see declaration of 'T'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2976: 'QTypeTraits::detail::has_operator_equal': too few template arguments
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(239): note: see declaration of 'QTypeTraits::detail::has_operator_equal'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2059: syntax error: 'function-style cast'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2143: syntax error: missing ';' before '{'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(274): error C2447: '{': missing function header (old-style formal list?)
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2039: 'variant': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\tuple(24): note: see declaration of 'std'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2065: 'variant': undeclared identifier
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2974: 'QTypeTraits::detail::expand_operator_equal_tuple': invalid template argument for 'T', type expected
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(272): note: see declaration of 'QTypeTraits::detail::expand_operator_equal_tuple'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2988: unrecognizable template declaration/definition
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2143: syntax error: missing ';' before '>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C3855: 'QTypeTraits::detail::expand_operator_equal_tuple': template parameter 'T' is incompatible with the declaration
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2059: syntax error: '>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2065: 'T': undeclared identifier
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C3544: 'T': parameter pack expects a type template argument
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2059: syntax error: '{'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2143: syntax error: missing ';' before '{'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(280): error C2447: '{': missing function header (old-style formal list?)
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2039: 'variant': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\tuple(24): note: see declaration of 'std'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2065: 'variant': undeclared identifier
       C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2974: 'QTypeTraits::detail::expand_operator_less_than_tuple': invalid     template argument for 'T', type expected
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(312): note: see declaration of 'QTypeTraits::detail::expand_operator_less_than_tuple'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2988: unrecognizable template declaration/definition
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2143: syntax error: missing ';' before '>'
      C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C3855: 'QTypeTraits::detail::expand_operator_less_than_tuple': template     parameter 'T' is incompatible with the declaration
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2059: syntax error: '>'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2065: 'T': undeclared identifier
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C3544: 'T': parameter pack expects a type template argument
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2059: syntax error: '{'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2143: syntax error: missing ';' before '{'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(318): error C2447: '{': missing function header (old-style formal list?)
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(330): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(335): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(340): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(363): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(371): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qtypeinfo.h(374): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(289): error C3533: a parameter cannot have a type that contains 'auto'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(289): note: 'auto' in non-type template parameters requires at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(299): error C3533: a parameter cannot have a type that contains 'auto'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(299): note: 'auto' in non-type template parameters requires at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(351): error C3533: a parameter cannot have a type that contains 'auto'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qnumeric.h(351): note: 'auto' in non-type template parameters requires at least '/std:c++17'
    D:\gradle-qt-application-example-master\src\main\cpp\untitled.cpp(4): warning C4273: 'Untitled::Untitled': inconsistent dll linkage
    D:\gradle-qt-application-example-master\src\main\meta-headers\untitled.h(9): note: see previous definition of '{ctor}'

    > Task :compileDebugWindowsCpp FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileDebugWindowsCpp'.
    > A build operation failed.
      C++ compiler failed while compiling untitled.cpp.
      See the complete log at: file:///D:/gradle-qt-application-example-master/build/tmp/compileDebugWindowsCpp/output.txt
       > C++ compiler failed while compiling untitled.cpp.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full     insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 29s
    4 actionable tasks: 4 executed
    10:36:55: Task execution finished ':assemble'.

**What I did wrong in this ? How can I solve this error ?**

  [1]: https://github.com/harideva16/qtlib
  [2]: https://github.com/harideva16/qtlib/blob/main/build.gradle

**Comment by axmetishe** [comment]
There's nothing related to qt plugin or application example repository - you got clear cpp compilation errors, please follow them.

**Comment by axmetishe** [comment]
Closing this since this is not a plugin issue nor example issue, just general cpp compilation errors which are not related to this or plugin repository.
