### ISSUE TITLE
[Question][Invalid] Add platform-specific linker args for mac os.

### ISSUE THREAD

**Issue by johnpawl** [axmetishe/gradle-qt-application-example#7]
How to add platform-specific linker args ?

**Comment by johnpawl** [comment]
check this : https://github.com/johnpawl/qt-github-action/runs/3673290798?check_suite_focus=true

**Comment by axmetishe** [comment]
@johnpawl 

- https://github.com/gradle/native-samples
- https://docs.gradle.org/current/userguide/building_cpp_projects.html
- https://docs.gradle.org/current/userguide/cpp_library_plugin.html
- https://docs.gradle.org/current/userguide/cpp_application_plugin.html
